name: Minify Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: auto minify the files
      uses: nizarmah/auto-minify@v3
      with:
        overwrite: true
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        branch: minify
        create_branch: true
