name: Compress and Minify Assets

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install compress-images imagemin-pngquant imagemin-webp

    - name: Minify CSS and JS files
      uses: JossyDevers/minify-js@v1.0.1
      with:
        directory: '.'
        output: '.'
        add_suffix: false
        inclusions: |
          .*\.css$
          .*\.js$

    - name: Compress images
      run: |
        node -e "
          const compress_images = require('compress-images');
          compress_images('**/*.{png,PNG,ico,ICO,webp,WEBP}', 'compressed/', {compress_force: false, statistic: true, autoupdate: true}, false,
            {png: {engine: 'pngquant', command: ['--quality=20-50']}}, 
            {ico: {engine: 'pngquant', command: ['--quality=20-50']}}, 
            {webp: {engine: 'cwebp', command: ['-q', '50']}}, 
            {}, 
            function(error) { 
              if (error) console.error('Error:', error); 
              else console.log('Images compressed successfully!'); 
            }
          );
        "

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Minified and compressed assets'
        branch: static
        file_pattern: |
          *.css
          *.js
          compressed/**
        commit_user_name: github-actions
        commit_user_email: github-actions@github.com
        token: ${{ secrets.GITHUB_TOKEN }}
