name: Minify and Compress Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Minify CSS
        uses: cssnano/cssnano-action@v2
        with:
          # Optional: Path to your CSS files, defaults to '**/*.css'
          source: .

      - name: Minify JS
        uses: runcloud/action-js-minify@v1
        with:
          # Optional: Path to your JS files, defaults to '**/*.js'
          source: .

      - name: Optimize PNG Images
        uses: JakeBolam/pongo@v1.1.2
        with:
          source: .
          # Optional: Path to your PNG files, defaults to '**/*.png'

      - name: Optimize ICO Images
        uses: JakeBolam/pongo@v1.1.2
        with:
          source: .
          # Optional: Path to your ICO files, defaults to '**/*.ico'

      - name: Optimize WebP Images
        uses: JakeBolam/pongo@v1.1.2
        with:
          source: .
          # Optional: Path to your WebP files, defaults to '**/*.webp'

      - name: Deploy to static branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: static
          force_orphan: true
