name: Compress and Minify Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install imagemin imagemin-pngquant imagemin-webp imagemin-mozjpeg

    - name: Minify CSS and JS files
      uses: JossyDevers/minify-js@v1.0.1
      with:
        directory: '.'
        output: '.'
        add_suffix: false
        inclusions: |
          .*\.css$
          .*\.js$

    - name: Compress images
      run: |
        node -e "
          const imagemin = require('imagemin');
          const imageminPngquant = require('imagemin-pngquant');
          const imageminWebp = require('imagemin-webp');
          const imageminMozjpeg = require('imagemin-mozjpeg');

          (async () => {
            await imagemin(['**/*.{png,PNG,ico,ICO,webp,WEBP}'], {
              destination: 'compressed/',
              plugins: [
                imageminPngquant({
                  quality: [0.2, 0.5]
                }),
                imageminWebp({
                  quality: 50
                }),
                imageminMozjpeg({
                  quality: 75
                })
              ]
            });
            console.log('Images compressed successfully!');
          })();
        "

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Minified and compressed assets'
        branch: static
        file_pattern: |
          *.css
          *.js
          compressed/**
        commit_user_name: github-actions
        commit_user_email: github-actions@github.com
        token: ${{ secrets.GITHUB_TOKEN }}
