name: Minify and Compress

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g clean-css-cli terser imagemin imagemin-cli imagemin-pngquant imagemin-mozjpeg imagemin-webp

    - name: Minify CSS
      run: |
        for file in *.css; do
          cleancss -o "$file" "$file"
        done

    - name: Minify JS
      run: |
        for file in *.js; do
          terser "$file" -o "$file"
        done

    - name: Compress images
      run: imagemin *.{png,ico,webp} --out-dir=.

    - name: Checkout static branch
      run: |
        git checkout -b static || git checkout static
        git pull origin static || echo "No static branch"

    - name: Sync files to static branch
      run: |
        rsync -av --exclude='.git*' --exclude='node_modules' --exclude='.github' . .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Minify CSS/JS and compress images' || echo "No changes to commit"
        git push origin static --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
