name: Minify and Compress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g clean-css-cli terser imagemin imagemin-cli imagemin-pngquant imagemin-mozjpeg imagemin-webp

    - name: Minify CSS
      run: cleancss -o styles.min.css styles.css

    - name: Minify JS
      run: terser script.js -o script.min.js

    - name: Compress images
      run: imagemin images/*.{png,ico,webp} --out-dir=compressed-images

    - name: Commit minified and compressed files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        mkdir -p static
        mv styles.min.css static/styles.min.css
        mv script.min.js static/script.min.js
        cp compressed-images/* static/
        git checkout -b static
        git add static/*
        git commit -m 'Minify CSS/JS and compress images'
        git push -f origin static
