name: Minify Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: auto minify the files
      uses: nizarmah/auto-minify@v3
      with:
        overwrite: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: minify
