name: Minify and Compress Assets

on:
  push:
    branches:
      - main # 替换成你存放源码的分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm install uglify-js clean-css imagemin-pngquant imagemin-webp imagemin-cli

      - name: Minify CSS
        run: npx clean-css --output static/style.css style.css

      - name: Minify JS
        run: npx uglifyjs script.js -o static/script.js

      - name: Compress images
        run: |
          npx imagemin *.png static --plugin=pngquant
          npx imagemin *.ico static --plugin=pngquant
          npx imagemin *.webp static --plugin=webp

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Compress assets'
          add: 'static/*'
          branch: static

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: static
