name: Optimize Assets

on:
  push:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Minify CSS and JS files
      - name: Minify CSS, JS, and HTML
        uses: amireshoon/minifyAction@v1.1
        with:
          repo: ${{ github.repository }}

      # Compress PNG, ICO, and WebP images
      - name: Compress Images
        uses: crush-pics/crush-pics-github-action@v1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}

      # Push changes to the static branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: static
          force: true
          commit_message: "Optimize CSS, JS, and images"
