name: Minify and Compress Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn add css-minify uglify-js imagemin-cli imagemin-pngquant imagemin-webp imagemin-zopfli

    - name: Minify CSS
      run: |
        mkdir -p minified
        for file in *.css; do
          css-minify -f $file -o minified/
        done

    - name: Minify JS
      run: |
        for file in *.js; do
          uglifyjs $file -o minified/$file --compress --mangle
        done

    - name: Compress Images
      run: |
        imagemin *.png *.ico *.webp --plugin=pngquant --plugin=webp --plugin=zopfli --out-dir=minified

    - name: Push to static branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b static
        mv minified/* .
        git add .
        git commit -m "Minify and compress assets"
        git push --force --set-upstream origin static
